version: '3.8'

services:
  anytime-roadtrips-app:
    image: anytime-roadtrips-app:latest
    container_name: anytime-roadtrips-app
    depends_on:
      - postgresdb
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    restart: always
    volumes:
      - anytime-roadtrips-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

volumes:
  anytime-roadtrips-db-data:
