version: '3.8'

services:
  anytime-roadtrips-app:
    image: anytime-roadtrips-app
    container_name: anytime-roadtrips-app
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=local
#      - POSTGRES_DB=roadtrips
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=password
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
#    networks:
#      - anytime-roadtrips-network

  postgres:
    image: postgres:alpine
    hostname: postgres
    restart: always
    volumes:
      - anytime-roadtrips-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
#    networks:
#      - anytime-roadtrips-network

volumes:
  anytime-roadtrips-db-data:

#networks:
#  anytime-roadtrips-network: