CREATE SCHEMA IF NOT EXISTS roadtrips;

CREATE TABLE IF NOT EXISTS "cars"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at"   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    "uuid"         VARCHAR(255)                            NOT NULL,
    "number_plate" VARCHAR(255)                            NOT NULL,
    CONSTRAINT "cars_pkey" PRIMARY KEY ("id")
);


